# Action for the IGPageContentValidator to check any HTML errors on the IG webpage
name: run HTML Error Checker

on: 
  push:
    paths:
      - IGPageContentValidator/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repo content
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./IGPageContentValidator/requirements.txt
        
      - name: Execute HTML Error Check 
        run: python ./IGPageContentValidator/errorChecker.py
    
