name: run linkchecker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt install python3-bs4 python3-dnspython python3-requests
          pip3 install linkchecker

        
      - name: execute linkchecker 
        run: linkchecker -r 2 --check-extern -f linkcheckerrc https://simplifier.net/guide/UK-Core-Implementation-Guide-STU3-Sequence/Home?version=current
        
        
