name: run linkchecker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt install python3-bs4 python3-dnspython python3-requests
          pip3 install linkchecker

      - name: Check link
        run: |
          wget -q --spider $(head -n 1 ./actions/website.txt)
      
      - name: execute linkchecker 
        run: |
          linkchecker -r 2 --check-extern --no-status -f linkcheckerrc $(head -n 1 ./actions/website.txt) || test $? = 1;
                
        
        
