name: run linkchecker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt install python3-bs4 python3-dnspython python3-requests
          pip3 install linkchecker

        
      - name: execute linkchecker 
        run: |
          echo ##### NOTE: JOB WILL FAIL IF BROKEN LINK IS FOUND ##### 
          linkchecker -r 2 --check-extern --no-status -f linkcheckerrc $(head -n 1 website.txt) || test $? = 1;
                
        
        
