name: run Spellchecker

on: 
  push:
    paths:
      - IGValidator/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt install aspell
          python -m pip install --upgrade pip
          pip install -r ./IGValidator/requirements.txt
        
      - name: execute LinkFinder.py 
        run: |
          python ./IGValidator/LinkFinder.py
          
      - name: execute Aspell spellchecker
        run: |
          #aspell dump dicts
          cat OutputLinks.txt | while read p; do wget -nv -O - $p | aspell list -H  --camel-case --lang en_GB --add-html-skip=nocheck -p ./actions/.aspell.en.pws |sort| uniq -c; echo -e '\n'; done;
    
